// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'Firebase iOS must be reconfigured for bundle com.example.ditto. '
          'The previous com.example.gameWiki Firebase app mapping was removed.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXHPcGxm5mCboZDSLE5YZvR_BwHyEbu2U',
    appId: '1:14378781761:web:494fbdafb1e3ee52614ac0',
    messagingSenderId: '14378781761',
    projectId: 'ditto-app-project',
    authDomain: 'ditto-app-project.firebaseapp.com',
    storageBucket: 'ditto-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWiRD-2WPw7ABF9ceniA2M_TOq0VaOFk',
    appId: '1:14378781761:android:0a5e0306a5894f1d614ac0',
    messagingSenderId: '14378781761',
    projectId: 'ditto-app-project',
    storageBucket: 'ditto-app-project.firebasestorage.app',
  );
}
